/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "docs/tech" }],

  // But you can create a sidebar manually

  tech: [
    "index",
    {
      type: "category",
      label: "Test Folder",
      link: {
        type: "doc",
        id: "test-folder/index",
      },
      items: [
        {
          type: "category",
          label: "Further test",
          link: { type: "doc", id: "test-folder/further-test/index"},
          items: ["test-folder/further-test/testing123"],
        }
      ]
    },
    {
      type: "category",
      label: "🧾 Cheat Sheets",
      link: {
        type: "doc",
        id: "cheats",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "cheats",
        },
      ],
    },
  ],
};

module.exports = sidebars;
